export const MyCourses = [
  {
    id: 1,
    CRN: 'HNRS4920',
    title: 'REAL Projects',
    description: 'R.E.A.L. Projects are student-led, multidisciplinary teams who work on a semester-long project submitted by companies and organizations interested in working with Weber State University students. R.E.A.L. Projects is a for-credit class focused on project management.',
    instructor: 'Robert Ameling',
    creditHours: 3,
    semester: 'Fall',
    year: 2020,
    posterImage: 'https://cdn.pixabay.com/photo/2015/01/09/02/45/laptop-593673_960_720.jpg',
    beginDate: new Date("2020, 08, 24"),
    endDate: new Date("2020, 12, 04"),
    added_at: new Date(),
    updated_at: new Date()
  },
  {
    id: 2,
    CRN: 'WEB4860',
    title: 'Internship',
    description: 'Students work in the web and user experience field.  The student fulfills  objectives that have been approved by a business/organization supervisor and a faculty advisor.',
    instructor: 'Cody Squadroni',
    creditHours: 3,
    semester: 'Fall',
    year: 2020,
    posterImage: 'https://cdn.pixabay.com/photo/2015/05/08/14/47/seo-758264_960_720.jpg',
    beginDate: new Date("2020, 08, 24"),
    endDate: new Date("2020, 12, 04"),
    added_at: new Date(),
    updated_at: new Date()
  },
  {
    id: 3,
    CRN: 'WEB3430',
    title: 'Full Stack Javascript Development',
    description: 'Modern web development increasingly involves using end-to-end JavaScript-based technologies such as MongoDB, Express.js, Angular, React, Vue.js, Node.js, etc. This course introduces development techniques that capitalize on the strengths of every layer in this JavaScript-based full-stack.',
    instructor: 'Abdulmalek Al-Gahmi',
    creditHours: 3,
    semester: 'Fall',
    year: 2020,
    posterImage: 'https://cdn.pixabay.com/photo/2015/06/24/15/45/code-820275_960_720.jpg',
    beginDate: new Date("2020, 08, 24"),
    endDate: new Date("2020, 12, 04"),
    added_at: new Date(),
    updated_at: new Date()
  },
  {
    id: 4,
    CRN: 'WEB2410',
    title: 'Web Animation 1',
    description: 'This course introduces various web technologies that aid the creation of web animations for distribution on many platforms. Students discuss technical issues affecting animation such as speed and compression. Students will explore several current tools to create animations for the web.',
    instructor: 'Thomas Bell',
    creditHours: 3,
    semester: 'Fall',
    year: 2020,
    posterImage: 'https://cdn.pixabay.com/photo/2015/06/24/16/36/office-820390_960_720.jpg',
    beginDate: new Date("2020, 08, 24"),
    endDate: new Date("2020, 12, 04"),
    added_at: new Date(),
    updated_at: new Date()
  },
  {
    id: 5,
    CRN: 'MKTG3010',
    title: 'Marketing Concepts and Practices',
    description: 'This course includes planning, implementation, and control of the marketing process; consumer behavior; marketing research; segmentation and target marketing; and consideration of price, place, and promotion.',
    instructor: 'Charles Durbin',
    creditHours: 3,
    semester: 'Summer',
    year: 2020,
    posterImage: 'https://cdn.pixabay.com/photo/2017/10/17/14/10/financial-2860753_960_720.jpg',
    beginDate: new Date("2020, 05, 04"),
    endDate: new Date("2020, 08, 07"),
    added_at: new Date(),
    updated_at: new Date()
  },
  {
    id: 6,
    CRN: 'PS3250',
    title: 'Business Communication',
    description: 'Application of oral and written communication, including diversity and international aspects of communication.',
    instructor: 'Brock Adams',
    creditHours: 3,
    semester: 'Summer',
    year: 2020,
    posterImage: 'https://cdn.pixabay.com/photo/2016/03/09/09/22/workplace-1245776_960_720.jpg',
    beginDate: new Date("2020, 05, 04"),
    endDate: new Date("2020, 08, 07"),
    added_at: new Date(),
    updated_at: new Date()
  }
]